"""Type stubs for the Wickra public API."""

from __future__ import annotations

from typing import Any, Mapping, Optional, Tuple, Union

import numpy as np
from numpy.typing import NDArray

__version__: str

CandleLike = Union[
    Tuple[float, float, float, float, float, int],
    Mapping[str, Any],
]

class SMA:
    def __init__(self, period: int) -> None: ...
    def update(self, value: float) -> Optional[float]: ...
    def batch(self, prices: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def reset(self) -> None: ...
    def is_ready(self) -> bool: ...
    def warmup_period(self) -> int: ...
    @property
    def period(self) -> int: ...
    @property
    def value(self) -> Optional[float]: ...

class EMA:
    def __init__(self, period: int) -> None: ...
    def update(self, value: float) -> Optional[float]: ...
    def batch(self, prices: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def reset(self) -> None: ...
    def is_ready(self) -> bool: ...
    def warmup_period(self) -> int: ...
    @property
    def period(self) -> int: ...
    @property
    def alpha(self) -> float: ...
    @property
    def value(self) -> Optional[float]: ...

class WMA:
    def __init__(self, period: int) -> None: ...
    def update(self, value: float) -> Optional[float]: ...
    def batch(self, prices: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def reset(self) -> None: ...
    def is_ready(self) -> bool: ...
    def warmup_period(self) -> int: ...
    @property
    def period(self) -> int: ...
    @property
    def value(self) -> Optional[float]: ...

class RSI:
    def __init__(self, period: int = 14) -> None: ...
    def update(self, value: float) -> Optional[float]: ...
    def batch(self, prices: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def reset(self) -> None: ...
    def is_ready(self) -> bool: ...
    def warmup_period(self) -> int: ...
    @property
    def period(self) -> int: ...
    @property
    def value(self) -> Optional[float]: ...

class MACD:
    def __init__(self, fast: int = 12, slow: int = 26, signal: int = 9) -> None: ...
    def update(self, value: float) -> Optional[Tuple[float, float, float]]: ...
    def batch(self, prices: NDArray[np.float64]) -> NDArray[np.float64]:
        """Returns shape ``(n, 3)`` with columns ``[macd, signal, histogram]``. NaN during warmup."""
        ...
    def reset(self) -> None: ...
    def is_ready(self) -> bool: ...
    def warmup_period(self) -> int: ...
    @property
    def periods(self) -> Tuple[int, int, int]: ...

class BollingerBands:
    def __init__(self, period: int = 20, multiplier: float = 2.0) -> None: ...
    def update(self, value: float) -> Optional[Tuple[float, float, float, float]]: ...
    def batch(self, prices: NDArray[np.float64]) -> NDArray[np.float64]:
        """Returns shape ``(n, 4)`` with columns ``[upper, middle, lower, stddev]``."""
        ...
    def reset(self) -> None: ...
    def is_ready(self) -> bool: ...
    def warmup_period(self) -> int: ...
    @property
    def period(self) -> int: ...
    @property
    def multiplier(self) -> float: ...

class ATR:
    def __init__(self, period: int = 14) -> None: ...
    def update(self, candle: CandleLike) -> Optional[float]: ...
    def batch(
        self,
        high: NDArray[np.float64],
        low: NDArray[np.float64],
        close: NDArray[np.float64],
    ) -> NDArray[np.float64]: ...
    def reset(self) -> None: ...
    def is_ready(self) -> bool: ...
    def warmup_period(self) -> int: ...
    @property
    def period(self) -> int: ...

class Stochastic:
    def __init__(self, k_period: int = 14, d_period: int = 3) -> None: ...
    def update(self, candle: CandleLike) -> Optional[Tuple[float, float]]: ...
    def batch(
        self,
        high: NDArray[np.float64],
        low: NDArray[np.float64],
        close: NDArray[np.float64],
    ) -> NDArray[np.float64]:
        """Returns shape ``(n, 2)`` with columns ``[k, d]``."""
        ...
    def reset(self) -> None: ...
    def is_ready(self) -> bool: ...
    def warmup_period(self) -> int: ...
    @property
    def periods(self) -> Tuple[int, int]: ...

class OBV:
    def __init__(self) -> None: ...
    def update(self, candle: CandleLike) -> Optional[float]: ...
    def batch(
        self,
        close: NDArray[np.float64],
        volume: NDArray[np.float64],
    ) -> NDArray[np.float64]: ...
    def reset(self) -> None: ...
    def is_ready(self) -> bool: ...
    def warmup_period(self) -> int: ...
    @property
    def value(self) -> Optional[float]: ...
