"""Wickra: streaming-first technical indicators.

Every indicator is available both in streaming mode (call ``update(value)`` per
new data point) and batch mode (call ``batch(numpy_array)`` over a full series).
Warmup positions in batch output are returned as ``NaN`` so the shape always
matches the input.

Example::

    import numpy as np
    import wickra as ta

    prices = np.linspace(100, 200, 1000)
    rsi = ta.RSI(14)
    values = rsi.batch(prices)        # numpy array, NaN during warmup

    # Or streaming:
    rsi = ta.RSI(14)
    for p in prices:
        v = rsi.update(p)             # None during warmup, then float

"""

from __future__ import annotations

from ._wickra import (
    __version__,
    # Trend
    SMA,
    EMA,
    WMA,
    DEMA,
    TEMA,
    HMA,
    KAMA,
    SMMA,
    TRIMA,
    ZLEMA,
    T3,
    VWMA,
    ALMA,
    McGinleyDynamic,
    FRAMA,
    VIDYA,
    JMA,
    Alligator,
    EVWMA,
    # Momentum
    RSI,
    MACD,
    Stochastic,
    CCI,
    ROC,
    WilliamsR,
    ADX,
    ADXR,
    MFI,
    TRIX,
    AwesomeOscillator,
    Aroon,
    MOM,
    CMO,
    TSI,
    PMO,
    TII,
    KST,
    StochRSI,
    UltimateOscillator,
    RVI,
    PGO,
    KST,
    SMI,
    LaguerreRSI,
    ConnorsRSI,
    Inertia,
    APO,
    AwesomeOscillatorHistogram,
    CFO,
    ZeroLagMACD,
    ElderImpulse,
    STC,
    PPO,
    DPO,
    Coppock,
    AroonOscillator,
    Vortex,
    RWI,
    WaveTrend,
    MassIndex,
    AcceleratorOscillator,
    BalanceOfPower,
    ChoppinessIndex,
    VerticalHorizontalFilter,
    # Volatility
    BollingerBands,
    ATR,
    Keltner,
    Donchian,
    PSAR,
    NATR,
    StdDev,
    UlcerIndex,
    HistoricalVolatility,
    BollingerBandwidth,
    PercentB,
    SuperTrend,
    ChandelierExit,
    ChandeKrollStop,
    AtrTrailingStop,
    HiLoActivator,
    VoltyStop,
    YoyoExit,
    DonchianStop,
    PercentageTrailingStop,
    StepTrailingStop,
    RenkoTrailingStop,
    TrueRange,
    ChaikinVolatility,
    RVIVolatility,
    ParkinsonVolatility,
    GarmanKlassVolatility,
    RogersSatchellVolatility,
    YangZhangVolatility,
    # Volume
    OBV,
    VWAP,
    RollingVWAP,
    ADL,
    VolumePriceTrend,
    ChaikinMoneyFlow,
    ChaikinOscillator,
    ForceIndex,
    KVO,
    VolumeOscillator,
    NVI,
    PVI,
    WilliamsAD,
    AnchoredVWAP,
    DemandIndex,
    TSV,
    VZO,
    MarketFacilitationIndex,
    EaseOfMovement,
    # Statistics
    TypicalPrice,
    MedianPrice,
    WeightedClose,
    LinearRegression,
    LinRegSlope,
    ZScore,
    LinRegAngle,
    # Bands & Channels
    MaEnvelope,
    AccelerationBands,
    StarcBands,
    AtrBands,
    HurstChannel,
    LinRegChannel,
    StandardErrorBands,
    DoubleBollinger,
    TtmSqueeze,
    FractalChaosBands,
    VwapStdDevBands,
    # Pivots & S/R
    ClassicPivots,
    FibonacciPivots,
    Camarilla,
    WoodiePivots,
    DemarkPivots,
    WilliamsFractals,
    ZigZag,
    # DeMark
    TDSetup,
    TDSequential,
    TDDeMarker,
    TDREI,
    TDPressure,
    TDCombo,
    TDCountdown,
    TDLines,
    TDRangeProjection,
    TDDifferential,
    TDOpen,
    TDRiskLevel,
)

__all__ = [
    "__version__",
    # Trend
    "SMA",
    "EMA",
    "WMA",
    "DEMA",
    "TEMA",
    "HMA",
    "KAMA",
    "SMMA",
    "TRIMA",
    "ZLEMA",
    "T3",
    "VWMA",
    "ALMA",
    "McGinleyDynamic",
    "FRAMA",
    "VIDYA",
    "JMA",
    "Alligator",
    "EVWMA",
    # Momentum
    "RSI",
    "MACD",
    "Stochastic",
    "CCI",
    "ROC",
    "WilliamsR",
    "ADX",
    "ADXR",
    "MFI",
    "TRIX",
    "AwesomeOscillator",
    "Aroon",
    "MOM",
    "CMO",
    "TSI",
    "PMO",
    "TII",
    "KST",
    "StochRSI",
    "UltimateOscillator",
    "RVI",
    "PGO",
    "KST",
    "SMI",
    "LaguerreRSI",
    "ConnorsRSI",
    "Inertia",
    "APO",
    "AwesomeOscillatorHistogram",
    "CFO",
    "ZeroLagMACD",
    "ElderImpulse",
    "STC",
    "PPO",
    "DPO",
    "Coppock",
    "AroonOscillator",
    "Vortex",
    "RWI",
    "WaveTrend",
    "MassIndex",
    "AcceleratorOscillator",
    "BalanceOfPower",
    "ChoppinessIndex",
    "VerticalHorizontalFilter",
    # Volatility
    "BollingerBands",
    "ATR",
    "Keltner",
    "Donchian",
    "PSAR",
    "NATR",
    "StdDev",
    "UlcerIndex",
    "HistoricalVolatility",
    "BollingerBandwidth",
    "PercentB",
    "SuperTrend",
    "ChandelierExit",
    "ChandeKrollStop",
    "AtrTrailingStop",
    "HiLoActivator",
    "VoltyStop",
    "YoyoExit",
    "DonchianStop",
    "PercentageTrailingStop",
    "StepTrailingStop",
    "RenkoTrailingStop",
    "TrueRange",
    "ChaikinVolatility",
    "RVIVolatility",
    "ParkinsonVolatility",
    "GarmanKlassVolatility",
    "RogersSatchellVolatility",
    "YangZhangVolatility",
    # Volume
    "OBV",
    "VWAP",
    "RollingVWAP",
    "ADL",
    "VolumePriceTrend",
    "ChaikinMoneyFlow",
    "ChaikinOscillator",
    "ForceIndex",
    "KVO",
    "VolumeOscillator",
    "NVI",
    "PVI",
    "WilliamsAD",
    "AnchoredVWAP",
    "DemandIndex",
    "TSV",
    "VZO",
    "MarketFacilitationIndex",
    "EaseOfMovement",
    # Statistics
    "TypicalPrice",
    "MedianPrice",
    "WeightedClose",
    "LinearRegression",
    "LinRegSlope",
    "ZScore",
    "LinRegAngle",
    # Bands & Channels
    "MaEnvelope",
    "AccelerationBands",
    "StarcBands",
    "AtrBands",
    "HurstChannel",
    "LinRegChannel",
    "StandardErrorBands",
    "DoubleBollinger",
    "TtmSqueeze",
    "FractalChaosBands",
    "VwapStdDevBands",
    # Pivots & S/R
    "ClassicPivots",
    "FibonacciPivots",
    "Camarilla",
    "WoodiePivots",
    "DemarkPivots",
    "WilliamsFractals",
    "ZigZag",
    # DeMark
    "TDSetup",
    "TDSequential",
    "TDDeMarker",
    "TDREI",
    "TDPressure",
    "TDCombo",
    "TDCountdown",
    "TDLines",
    "TDRangeProjection",
    "TDDifferential",
    "TDOpen",
    "TDRiskLevel",
]
