/* Cross-language data-layer parity for the C / C++ binding: replay the shared
 * golden tick stream through the TickAggregator (push/drain) and check the
 * candles against the Rust reference, with and without gap filling. The same
 * source compiles under both a C and a C++ compiler. Fixtures are generated by
 * `cargo run -p wickra-examples --bin gen_golden`; the golden dir is argv[1].
 */
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "wickra.h"

#define MAXROWS 256

static const char *GDIR;

static int read_csv(const char *name, double *rows, int ncol) {
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s.csv", GDIR, name);
    FILE *f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", path);
        exit(2);
    }
    char line[4096];
    int n = 0, first = 1;
    while (fgets(line, sizeof(line), f)) {
        line[strcspn(line, "\r\n")] = '\0';
        if (first) {
            first = 0;
            continue;
        }
        if (line[0] == '\0') {
            continue;
        }
        char *p = line;
        for (int j = 0; j < ncol; j++) {
            rows[n * ncol + j] = strtod(p, &p);
            if (*p == ',') {
                p++;
            }
        }
        n++;
    }
    fclose(f);
    return n;
}

static int check(const char *fixture, bool gap, const double *ticks, int nt) {
    struct TickAggregator *a = wickra_tick_aggregator_new(1000, gap);
    if (!a) {
        printf("FAIL %s: new returned NULL\n", fixture);
        return 1;
    }
    double want[MAXROWS * 6];
    int nw = read_csv(fixture, want, 6);
    double got[MAXROWS * 6];
    int ng = 0;
    for (int i = 0; i < nt; i++) {
        intptr_t n = wickra_tick_aggregator_push(a, ticks[i * 3 + 0], ticks[i * 3 + 1],
                                                 (int64_t)ticks[i * 3 + 2]);
        if (n > 0) {
            struct WickraCandle buf[MAXROWS];
            intptr_t w = wickra_tick_aggregator_drain(a, buf, (uintptr_t)n);
            for (intptr_t j = 0; j < w; j++) {
                got[ng * 6 + 0] = buf[j].open;
                got[ng * 6 + 1] = buf[j].high;
                got[ng * 6 + 2] = buf[j].low;
                got[ng * 6 + 3] = buf[j].close;
                got[ng * 6 + 4] = buf[j].volume;
                got[ng * 6 + 5] = (double)buf[j].timestamp;
                ng++;
            }
        }
    }
    wickra_tick_aggregator_free(a);
    if (ng != nw) {
        printf("FAIL %s: %d candles vs %d\n", fixture, ng, nw);
        return 1;
    }
    int fails = 0;
    for (int i = 0; i < ng; i++) {
        for (int j = 0; j < 6; j++) {
            double w = want[i * 6 + j];
            double tol = 1e-9 * fmax(1.0, fabs(w));
            if (fabs(got[i * 6 + j] - w) > tol) {
                printf("FAIL %s row %d col %d: %g vs %g\n", fixture, i, j, got[i * 6 + j], w);
                fails++;
            }
        }
    }
    return fails;
}

int main(int argc, char **argv) {
    GDIR = (argc > 1) ? argv[1] : "testdata/golden";
    double ticks[MAXROWS * 3];
    int nt = read_csv("data_ticks", ticks, 3);
    int fails = check("data_candles", false, ticks, nt);
    fails += check("data_candles_gap", true, ticks, nt);
    if (fails == 0) {
        printf("C/C++ data layer: OK (%d ticks)\n", nt);
    }
    return fails ? 1 : 0;
}
