# Golden-fixture parity: replay the shared testdata/golden input series through
# the R FFI and assert every value matches the Rust reference output. Where the
# archetype test only checks finiteness, this pins exact values, catching wiring
# bugs (swapped params, wrong multi-output field). Fixtures are generated by
# `cargo run -p wickra-examples --bin gen_golden`.

golden_dir <- local({
  d <- normalizePath(getwd(), winslash = "/", mustWork = FALSE)
  repeat {
    g <- file.path(d, "testdata", "golden")
    if (dir.exists(g)) return(g)
    parent <- dirname(d)
    if (identical(parent, d)) stop("testdata/golden not found from ", getwd())
    d <- parent
  }
})

read_golden <- function(name) {
  read.csv(file.path(golden_dir, paste0(name, ".csv")),
           colClasses = "character", check.names = FALSE)
}

gcell <- function(s) if (identical(s, "nan")) NA_real_ else as.numeric(s)

expect_close <- function(got, want, row, field) {
  if (is.na(want)) {
    expect_true(is.na(got), info = paste("row", row, field, "expected warmup/NA"))
  } else {
    tol <- 1e-6 * max(1, abs(want))
    expect_lte(abs(got - want), tol, label = paste("row", row, field, "got", got, "want", want))
  }
}

golden_input <- read.csv(file.path(golden_dir, "input.csv"))

test_that("scalar indicators match golden", {
  specs <- list(c("sma", 14), c("ema", 14), c("rsi", 14))
  for (spec in specs) {
    name <- spec[[1]]
    ind <- switch(name, sma = Sma(14), ema = Ema(14), rsi = Rsi(14))
    exp <- read_golden(name)
    for (i in seq_len(nrow(golden_input))) {
      got <- update(ind, golden_input$close[i])
      expect_close(got, gcell(exp[i, 1]), i, name)
    }
  }
})

test_that("candle Atr matches golden", {
  atr <- Atr(14)
  exp <- read_golden("atr")
  for (i in seq_len(nrow(golden_input))) {
    got <- update(atr, golden_input$open[i], golden_input$high[i], golden_input$low[i],
                  golden_input$close[i], golden_input$volume[i], i - 1)
    expect_close(got, gcell(exp[i, 1]), i, "atr")
  }
})

test_that("pairwise Beta matches golden", {
  beta <- Beta(20)
  exp <- read_golden("beta")
  for (i in seq_len(nrow(golden_input))) {
    # generator fed (close, open)
    got <- update(beta, golden_input$close[i], golden_input$open[i])
    expect_close(got, gcell(exp[i, 1]), i, "beta")
  }
})

test_that("multi-output MACD matches golden", {
  macd <- MacdIndicator(12, 26, 9)
  exp <- read_golden("macd")
  for (i in seq_len(nrow(golden_input))) {
    out <- update(macd, golden_input$close[i])
    if (identical(exp[i, "macd"], "nan")) {
      expect_true(all(is.na(out)), info = paste("row", i, "macd warmup"))
    } else {
      expect_close(out[["macd"]], gcell(exp[i, "macd"]), i, "macd.macd")
      expect_close(out[["signal"]], gcell(exp[i, "signal"]), i, "macd.signal")
      expect_close(out[["histogram"]], gcell(exp[i, "histogram"]), i, "macd.histogram")
    }
  }
})

test_that("multi-output ADX matches golden", {
  adx <- Adx(14)
  exp <- read_golden("adx")
  for (i in seq_len(nrow(golden_input))) {
    out <- update(adx, golden_input$open[i], golden_input$high[i], golden_input$low[i],
                  golden_input$close[i], golden_input$volume[i], i - 1)
    if (identical(exp[i, "plus_di"], "nan")) {
      expect_true(all(is.na(out)), info = paste("row", i, "adx warmup"))
    } else {
      expect_close(out[["plus_di"]], gcell(exp[i, "plus_di"]), i, "adx.plus_di")
      expect_close(out[["minus_di"]], gcell(exp[i, "minus_di"]), i, "adx.minus_di")
      expect_close(out[["adx"]], gcell(exp[i, "adx"]), i, "adx.adx")
    }
  }
})
