//! Built-in indicators. Every indicator implements [`crate::Indicator`].
//!
//! Modules are organised internally by category (trend, momentum, volatility,
//! volume) but every public name is also re-exported flat from this module and
//! from the crate root for convenience.

mod accelerator_oscillator;
mod adl;
mod adx;
mod alpha;
mod aroon;
mod aroon_oscillator;
mod atr;
mod atr_trailing_stop;
mod average_drawdown;
mod awesome_oscillator;
mod balance_of_power;
mod bollinger;
mod bollinger_bandwidth;
mod calmar_ratio;
mod cci;
mod chaikin_oscillator;
mod chaikin_volatility;
mod chande_kroll_stop;
mod chandelier_exit;
mod choppiness_index;
mod cmf;
mod cmo;
mod conditional_value_at_risk;
mod coppock;
mod dema;
mod donchian;
mod dpo;
mod drawdown_duration;
mod ease_of_movement;
mod ema;
mod force_index;
mod gain_loss_ratio;
mod historical_volatility;
mod hma;
mod information_ratio;
mod kama;
mod kelly_criterion;
mod keltner;
mod linreg;
mod linreg_angle;
mod linreg_slope;
mod macd;
mod mass_index;
mod max_drawdown;
mod median_price;
mod mfi;
mod mom;
mod natr;
mod obv;
mod omega_ratio;
mod pain_index;
mod percent_b;
mod pmo;
mod ppo;
mod profit_factor;
mod psar;
mod recovery_factor;
mod roc;
mod rsi;
mod sharpe_ratio;
mod sma;
mod smma;
mod sortino_ratio;
mod std_dev;
mod stoch_rsi;
mod stochastic;
mod super_trend;
mod t3;
mod tema;
mod treynor_ratio;
mod trima;
mod trix;
mod true_range;
mod tsi;
mod typical_price;
mod ulcer_index;
mod ultimate_oscillator;
mod value_at_risk;
mod vertical_horizontal_filter;
mod vortex;
mod vpt;
mod vwap;
mod vwma;
mod weighted_close;
mod williams_r;
mod wma;
mod z_score;
mod zlema;

pub use accelerator_oscillator::AcceleratorOscillator;
pub use adl::Adl;
pub use adx::{Adx, AdxOutput};
pub use alpha::Alpha;
pub use aroon::{Aroon, AroonOutput};
pub use aroon_oscillator::AroonOscillator;
pub use atr::Atr;
pub use atr_trailing_stop::AtrTrailingStop;
pub use average_drawdown::AverageDrawdown;
pub use awesome_oscillator::AwesomeOscillator;
pub use balance_of_power::BalanceOfPower;
pub use bollinger::{BollingerBands, BollingerOutput};
pub use bollinger_bandwidth::BollingerBandwidth;
pub use calmar_ratio::CalmarRatio;
pub use cci::Cci;
pub use chaikin_oscillator::ChaikinOscillator;
pub use chaikin_volatility::ChaikinVolatility;
pub use chande_kroll_stop::{ChandeKrollStop, ChandeKrollStopOutput};
pub use chandelier_exit::{ChandelierExit, ChandelierExitOutput};
pub use choppiness_index::ChoppinessIndex;
pub use cmf::ChaikinMoneyFlow;
pub use cmo::Cmo;
pub use conditional_value_at_risk::ConditionalValueAtRisk;
pub use coppock::Coppock;
pub use dema::Dema;
pub use donchian::{Donchian, DonchianOutput};
pub use dpo::Dpo;
pub use drawdown_duration::DrawdownDuration;
pub use ease_of_movement::EaseOfMovement;
pub use ema::Ema;
pub use force_index::ForceIndex;
pub use gain_loss_ratio::GainLossRatio;
pub use historical_volatility::HistoricalVolatility;
pub use hma::Hma;
pub use information_ratio::InformationRatio;
pub use kama::Kama;
pub use kelly_criterion::KellyCriterion;
pub use keltner::{Keltner, KeltnerOutput};
pub use linreg::LinearRegression;
pub use linreg_angle::LinRegAngle;
pub use linreg_slope::LinRegSlope;
pub use macd::{MacdIndicator, MacdOutput};
pub use mass_index::MassIndex;
pub use max_drawdown::MaxDrawdown;
pub use median_price::MedianPrice;
pub use mfi::Mfi;
pub use mom::Mom;
pub use natr::Natr;
pub use obv::Obv;
pub use omega_ratio::OmegaRatio;
pub use pain_index::PainIndex;
pub use percent_b::PercentB;
pub use pmo::Pmo;
pub use ppo::Ppo;
pub use profit_factor::ProfitFactor;
pub use psar::Psar;
pub use recovery_factor::RecoveryFactor;
pub use roc::Roc;
pub use rsi::Rsi;
pub use sharpe_ratio::SharpeRatio;
pub use sma::Sma;
pub use smma::Smma;
pub use sortino_ratio::SortinoRatio;
pub use std_dev::StdDev;
pub use stoch_rsi::StochRsi;
pub use stochastic::{Stochastic, StochasticOutput};
pub use super_trend::{SuperTrend, SuperTrendOutput};
pub use t3::T3;
pub use tema::Tema;
pub use treynor_ratio::TreynorRatio;
pub use trima::Trima;
pub use trix::Trix;
pub use true_range::TrueRange;
pub use tsi::Tsi;
pub use typical_price::TypicalPrice;
pub use ulcer_index::UlcerIndex;
pub use ultimate_oscillator::UltimateOscillator;
pub use value_at_risk::ValueAtRisk;
pub use vertical_horizontal_filter::VerticalHorizontalFilter;
pub use vortex::{Vortex, VortexOutput};
pub use vpt::VolumePriceTrend;
pub use vwap::{RollingVwap, Vwap};
pub use vwma::Vwma;
pub use weighted_close::WeightedClose;
pub use williams_r::WilliamsR;
pub use wma::Wma;
pub use z_score::ZScore;
pub use zlema::Zlema;
