//! Built-in indicators. Every indicator implements [`crate::Indicator`].
//!
//! Modules are organised internally by category (trend, momentum, volatility,
//! volume) but every public name is also re-exported flat from this module and
//! from the crate root for convenience.

mod adx;
mod aroon;
mod aroon_oscillator;
mod atr;
mod awesome_oscillator;
mod bollinger;
mod cci;
mod cmo;
mod coppock;
mod dema;
mod donchian;
mod dpo;
mod ema;
mod hma;
mod kama;
mod keltner;
mod macd;
mod mass_index;
mod mfi;
mod mom;
mod obv;
mod pmo;
mod ppo;
mod psar;
mod roc;
mod rsi;
mod sma;
mod smma;
mod stoch_rsi;
mod stochastic;
mod t3;
mod tema;
mod trima;
mod trix;
mod tsi;
mod ultimate_oscillator;
mod vortex;
mod vwap;
mod vwma;
mod williams_r;
mod wma;
mod zlema;

pub use adx::{Adx, AdxOutput};
pub use aroon::{Aroon, AroonOutput};
pub use aroon_oscillator::AroonOscillator;
pub use atr::Atr;
pub use awesome_oscillator::AwesomeOscillator;
pub use bollinger::{BollingerBands, BollingerOutput};
pub use cci::Cci;
pub use cmo::Cmo;
pub use coppock::Coppock;
pub use dema::Dema;
pub use donchian::{Donchian, DonchianOutput};
pub use dpo::Dpo;
pub use ema::Ema;
pub use hma::Hma;
pub use kama::Kama;
pub use keltner::{Keltner, KeltnerOutput};
pub use macd::{MacdIndicator, MacdOutput};
pub use mass_index::MassIndex;
pub use mfi::Mfi;
pub use mom::Mom;
pub use obv::Obv;
pub use pmo::Pmo;
pub use ppo::Ppo;
pub use psar::Psar;
pub use roc::Roc;
pub use rsi::Rsi;
pub use sma::Sma;
pub use smma::Smma;
pub use stoch_rsi::StochRsi;
pub use stochastic::{Stochastic, StochasticOutput};
pub use t3::T3;
pub use tema::Tema;
pub use trima::Trima;
pub use trix::Trix;
pub use tsi::Tsi;
pub use ultimate_oscillator::UltimateOscillator;
pub use vortex::{Vortex, VortexOutput};
pub use vwap::{RollingVwap, Vwap};
pub use vwma::Vwma;
pub use williams_r::WilliamsR;
pub use wma::Wma;
pub use zlema::Zlema;
