/* Wickra C ABI — generated by cbindgen. Do not edit by hand. */

#ifndef WICKRA_H
#define WICKRA_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Simple Moving Average over a fixed window.
 *
 * Maintains a rolling sum so each update is O(1). Output equals
 * `sum(last `period` prices) / period` once the window is full; `None` before.
 *
 * On long-running streams a single-subtract incremental sum can accumulate
 * rounding error (catastrophic cancellation when values of very different
 * magnitudes are alternately added and removed). To keep drift bounded, the
 * running sum is reseeded from the live window every `16 · period` updates —
 * O(1) amortised cost (`O(period)` work amortised over `O(period)` updates),
 * zero observable behaviour change on inputs that did not drift to begin
 * with, and a strict cap on accumulated rounding for streams that did.
 *
 * # Example
 *
 * ```
 * use wickra_core::{Indicator, Sma};
 *
 * let mut indicator = Sma::new(3).unwrap();
 * let mut last = None;
 * for i in 0..80 {
 *     last = indicator.update(100.0 + f64::from(i));
 * }
 * assert!(last.is_some());
 * ```
 */
typedef struct Sma Sma;

/**
 * Create an `SMA` indicator with the given period.
 *
 * Returns `NULL` if the period is invalid (e.g. zero). The returned handle must
 * be released exactly once with [`wickra_sma_free`].
 */
struct Sma *wickra_sma_new(uintptr_t period);

/**
 * Feed one value and return the freshly computed output, or `NaN` while the
 * indicator is still warming up or if `handle` is `NULL`.
 *
 * # Safety
 * `handle` must be a valid pointer returned by [`wickra_sma_new`] and not yet
 * freed, or `NULL`.
 */
double wickra_sma_update(struct Sma *handle, double value);

/**
 * Run the indicator over `input[0..n]`, writing one output per input into
 * `out[0..n]`. Warmup positions are written as `NaN`. No-op if any pointer is
 * `NULL`.
 *
 * # Safety
 * `handle` must be valid (from [`wickra_sma_new`], not freed). `input` and `out`
 * must each point to at least `n` readable / writable `double`s.
 */
void wickra_sma_batch(struct Sma *handle, const double *input, double *out, uintptr_t n);

/**
 * Reset all internal state, equivalent to a freshly constructed indicator.
 * No-op if `handle` is `NULL`.
 *
 * # Safety
 * `handle` must be valid (from [`wickra_sma_new`], not freed), or `NULL`.
 */
void wickra_sma_reset(struct Sma *handle);

/**
 * Destroy a handle created by [`wickra_sma_new`]. No-op if `handle` is `NULL`.
 *
 * # Safety
 * `handle` must have been returned by [`wickra_sma_new`] and not previously
 * freed, or `NULL`. Using `handle` after this call is undefined behavior.
 */
void wickra_sma_free(struct Sma *handle);

#endif  /* WICKRA_H */
